sudo: required
before_install:
  - sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
  - sudo apt-get install -y libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y software-properties-common
  - sudo apt-get install -y git
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

language: cpp

compiler:
  - g++

install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - git clone --recursive https://github.com/sighttviewliu/myci.git myci
  - cd myci
  - git checkout master

branches:
  only:
  - master
  - dev
  - features/20180418

script:
  - make distclean
  - make
  - make distclean
  - rm makefile
  - ./build.sh
  - ./travis_qmake_gcc_cpp11_gcov
  - ./get_code_cov.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t a0eb1c5d-c253-407e-80a0-0630258f26b4

notifications:
  email:
    recipients:
      - denchance@gmail.com
    on_success: always
    on_failure: always
